struct FAsensors {
    long id; //@key
    long state;
    double AR_TS01_TP; // 300.15
    double AR_TS02_TP; // 300.15
    double AR_TS03_TP; // 300.15
    double AR_TS04_TP; // 300.15
    double AR_TS05_TP; // 300.15
    double AR_TS06_TP; // 300.15
    double AR_TS07_TP; // 300.15
    double AR_TS08_TP; // 300.15
    double AR_TS09_TP; // 300.15
    double AR_TS10_TP; // 300.15
    double AR_TS12_TP; // 300.15
    double AR_TS15_TP; // 300.15
    double AR_TS16_TP; // 300.15
    double AR_TS18_TP; // 300.15
    double AR_TS19_TP; // 300.15
    double AR_TS20_TP; // 278
    double AR_TS21_TP; // 300.15
    double AR_TC5_TP; // 300.15
    double AR_TC4_TP; // 300.15
    double AR_TC3_TP; // 300.15
    double AR_TC2_TP; // 300.15
    double AR_TS39_TP; // 300.15
    double AR_TS40_TP; // 300.15
    double AR_TS_Fn01_TP; // 300.15
    double AR_TS_Fn02_TP; // 300.15
    double AR_PS01_TP; // 101325
    double AR_PS02_TP; // 101325
    double AR_DP_Fn01_TP; // 0
    double AR_IS_Fn01_TP; // 0
    double AR_NS_Fn01_TP; // 0
    double AR_DP_Fn02_TP; // 0
    double AR_IS_Fn02_TP; // 0
    double AR_NS_Fn02_TP; // 0
    double AR_CO01_TP; // 0
    double AR_PI02_TP; // 1.33
    double AR_PI03_TP; // 0.73
    double AR_IS_Pp01_TP; // 0
    double AR_F_Vv01_TP; // 1
    double AR_DP_01_TP; // 0
    double AR_Sn01N2Pa_TP; // 0
    double AR_Sn01O2Pa_TP; // 21300
    double AR_Sn01H2OPa_TP; // 0
    double AR_Sn01ArPa_TP; // 0
    double AR_Sn01CO2Pa_TP; // 267
    double AR_Sn01CH4_TP; // 0.00002
    double AR_TC1_TP; // 300.15
    double AR_TC7_TP; // 300.15
    double AR_TC6_TP; // 300.15
    double AR_PI06_TP; // 0.729855
    double AR_TS47; // 300.15
    double AR_TS48; // 300.15
    double AR_TS49; // 300.15
    double AR_TS50; // 300.15
    double AR_TS52; // 300.15
    double AR_TS55; // 300.15
    double AR_TS56; // 300.15
    double AR_TS58; // 300.15
    double AR_PS03; // 101325
    double AR_PS04; // 101325
    double AR_PS70; // 101325
    double AR_TS70; // 300.15
    double AR_PS71; // 101325
    double AR_TS71; // 300.15
    double AR_PS72; // 101325
    double AR_FM72; // 0
    long fault;
};